# Site settings
title: "sitzExtase"
email: grallert@orient-institut.org
description: > # A blog on all things related to late Ottoman *Bilād al-Shām*, Arabic and Ottoman newspapers, and digital humanities
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tillgrallert.github.io" # the base hostname & protocol for your site
header-img: assets/header-img.jpg


# author information
author: Till Grallert
bio: "Research associate (PhD in History, Freie Universität Berlin, 2014) at Orient Institut Beirut. He is a student of the social and urban history of *Bilād al-Shām* in late Ottoman times. His currently works on a genealogy of food riots as a repertoire of contention between the mid-eighteenth and the mid-twentieth centuries"
orcid: 0000-0002-5739-8094

twitter_username: tillgrallert
github_username:  tillgrallert
disqus_shortname: sitzextase


# Build settings
# Outputting
permalink:  /blog/:year/:month/:day/:title/ # default value: date; built-in values: date, pretty, ordinal, none
paginate_path: /page:num
timezone:    null
quiet:    false
defaults: []
# excerpt_separator: <!--more-->

# Markdown settings
markdown: kramdown # pandoc

# pagination should work with "paginate: 5"

# Default values

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"
      author: Till Grallert

# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data

# Plugins
whitelist: []
gems: []
# - jekyll-pandoc  # jekyll-pandoc is not yet compatible with jekyll 3.0.0
# -jekyll-pandoc-multiple-formats; not yet supported by jekyll 3.0.0


## settings for jekyll-pandoc-multiple-formats
pandoc:
  skip: false
  impose: false
  output: ./tmp
  flags: '--smart'
  site_flags: '--toc'
  outputs:
    pdf: '--latex-engine=latex'
    epub:
    markdown: